Q1. Pandas version:
What version of Pandas did you install?

In [19]:
import pandas as pd
pd.__version__

'2.3.2'

Q2. Records count

In [20]:
# read data
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"
df = pd.read_csv(url)
print(df.head())

   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3         

In [21]:
print(df)

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel dr

Q2. Records count:
How many records are in the dataset?

In [22]:
rec_count = len(df)
print("No. of records in this dataset are:", rec_count)

No. of records in this dataset are: 9704


Q3. Fuel types: 
How many fuel types are presented in the dataset?

In [23]:
num_fuel_types = df['fuel_type'].nunique()
print("number of fuel types in this dataset are:", num_fuel_types)

number of fuel types in this dataset are: 2


Q4. Missing values:
How many columns in the dataset have missing values?

In [24]:
missing_val = df.isnull().sum()
print(missing_val)

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64


In [25]:
total_missing_val = (missing_val > 0).sum()
print("Columns with missing values:",total_missing_val)

Columns with missing values: 4


Q5. Max fuel efficiency: 
What's the maximum fuel efficiency of cars from Asia?

In [26]:
max_fuel = df[df['origin'] == 'Asia'] ['fuel_efficiency_mpg'].max()
print("the maximum fuel efficiency of cars from Asia:",max_fuel )

the maximum fuel efficiency of cars from Asia: 23.759122836520497


Q6. Median value of horsepower: 
 6.1 Find the median value of the horsepower column in the dataset.

In [27]:
median_hp = df['horsepower'].median()
print("the median value of the horsepower:", median_hp)

the median value of the horsepower: 149.0


    6.2 Next, calculate the most frequent value of the same horsepower column.

In [28]:
most_frequest_hp = df['horsepower'].mode()[0]
print("Most frquent horsepower value:",most_frequest_hp )

Most frquent horsepower value: 152.0


    6.3 Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [29]:
new_hp = df['horsepower'].fillna(most_frequest_hp)
print(new_hp) 

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64


Now, calculate the median value of horsepower once again.

In [30]:
new_median = new_hp.median()
print("the horsepower after filling missing values:", new_median) 

the horsepower after filling missing values: 152.0


#### Original median horsepower: 149.0
#### Most frequent horsepower value (mode): 152.0
#### New median after filling missing values with 152.0: 152.0
    
#### Has the median changed?

#### Yes, it increased.
#### This is because the mode (152.0) is higher than the original median (149.0), so filling missing values with 152.0 shifts the median upward.

Q7. Sum of weights

In [ ]:
# 7.1 Select all the cars from Asia &Select only columns vehicle_weight and model_year
asia_cars = df[df['origin'] == 'Asia'] [['vehicle_weight','model_year']]
print(asia_cars.head(7))

      vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]
    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019


In [32]:
# 7.2 Select the first 7 values & Get the underlying NumPy array. Let's call it X

X = asia_cars.head(7).values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [33]:
# 7.3  Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
import numpy as np
XTX = np.dot(X.T, X)
print(XTX)

[[62248334.33150762 41431216.5073268 ]
 [41431216.5073268  28373339.        ]]


In [34]:
# 7.4 Invert XTX. & Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

# Create array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)

[[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]
[1100 1300  800  900 1000 1100 1200]


In [35]:
# 7.4 Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w. 
W = np.dot(np.dot(XTX_inv, X.T),y)
print(W)

[0.01386421 0.5049067 ]


In [36]:
# 7.5 What's the sum of all the elements of the result?
sum_result = W.sum()
print("the sum:", sum_result)

the sum: 0.5187709081074016
